"""Initial revision

Revision ID: e59c33635a60
Revises: 
Create Date: 2017-11-07 21:48:14.017873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59c33635a60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=False),
    sa.Column('last_name', sa.String(length=45), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('address2', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=20), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('city',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], ),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=False),
    sa.Column('last_name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('film',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('release_year', sa.SmallInteger(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('original_language_id', sa.Integer(), nullable=True),
    sa.Column('rental_duration', sa.SmallInteger(), nullable=False),
    sa.Column('rental_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('length', sa.SmallInteger(), nullable=True),
    sa.Column('replacement_cost', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rating', sa.Enum('G', 'PG', 'PG_13', 'R', 'NC_17', name='mpaarating'), nullable=True),
    sa.Column('special_features', sa.String(length=255), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.language_id'], ),
    sa.ForeignKeyConstraint(['original_language_id'], ['language.language_id'], ),
    sa.PrimaryKeyConstraint('film_id')
    )
    op.create_table('film_actor',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], ),
    sa.PrimaryKeyConstraint('actor_id', 'film_id')
    )
    op.create_table('film_category',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], ),
    sa.PrimaryKeyConstraint('film_id', 'category_id')
    )
    op.create_table('inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_table('language',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('language_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['rental_id'], ['rental.rental_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('rental',
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('rental_date', sa.DateTime(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.inventory_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('rental_id')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=False),
    sa.Column('last_name', sa.String(length=45), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('store',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('manager_staff_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.ForeignKeyConstraint(['manager_staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    op.drop_table('staff')
    op.drop_table('rental')
    op.drop_table('payment')
    op.drop_table('language')
    op.drop_table('inventory')
    op.drop_table('film_category')
    op.drop_table('film_actor')
    op.drop_table('film')
    op.drop_table('customer')
    op.drop_table('country')
    op.drop_table('city')
    op.drop_table('category')
    op.drop_table('address')
    op.drop_table('actor')
    # ### end Alembic commands ###
